try {
    console.log(a + b);
} catch (err) {
    console.log(err);
    console.log('There is an error');
    console.log('The error was saved in the error log');
}

console.log("My program does not stop.");